spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: password
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate